# Copyright 2021 Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: Proofs

on:
  push:
    branches:
      - master
      - rt
  pull_request:

jobs:
  aspec:
    name: ASpec
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM, RISCV64]
    steps:
    - name: Proofs
      uses: seL4/ci-actions/aws-proofs@aws-proofs
      with:
        L4V_ARCH: ${{ matrix.arch }}
        isa_branch: ts-2020
        session: ASpec
